### ISSUE TITLE
Dependencies missing unless version is incremented

### ISSUE THREAD

**Issue by andrewbonney** [bbc/nmos-common#15]
Over multiple trials, the deb package dependencies 'python-flask-oauthlib' and 'python-flask-sockets' fail to be installed when installing the package. This is despite them correctly appearing in the Depends: line of the built .deb

I've noted that by incrementing the version in the Debian changelog (for example to 0.1.1) this starts working correctly. If you then decrement again and install the package it again omits these dependencies. I'm yet to fully understand why these two specific packages seem to strongly linked to this package's version.

**Comment by andrewbonney** [comment]
Updated the version as a workaround, but would still be keen to know why this happens.

**Comment by cnorthwood** [comment]
hmm, just installed 0.1.1 on a fresh node and I'm once again missing these dependencies, are they in the latest built debs?

**Comment by andrewbonney** [comment]
It appears they're not (having downloaded the deb and run `dpkg -I` against it). Yet for the same code a local build I had worked. Given I've had this issue locally too I'm not sure it's a local vs CI issue, but that may help to identify what's causing it.

**Comment by andrewbonney** [comment]
PR #25 adds a temporary fix. This does still need addressing properly however.

**Comment by andrewbonney** [comment]
Re-review https://github.com/bbc/nmos-common/pull/36 once the above is fixed. There are likely several overrides we don't require.

**Comment by andrewbonney** [comment]
I suspect this may have been resolved by the fact we no longer have a debian/control at all. Removing remaining false overrides to confirm.
