### ISSUE TITLE
API constructor failure not signalled in HTTPServer start

### ISSUE THREAD

**Issue by philipnbbc** [bbc/nmos-common#98]
If the API constructor raises an exception at https://github.com/bbc/nmos-common/blob/master/nmoscommon/httpserver.py#L43 then the HTTPServer thread exits but doesn't set `started` (and `failed`). A client that is waiting for `started` to be set will wait forever. A similar issue could arise if the socket calls raise an exception.

**Comment by jamesba** [comment]
Fixed in https://github.com/bbc/nmos-common/pull/107
